### ISSUE TITLE
Incorrect ZOD EventSpecifier

### ISSUE THREAD

**Issue by MaximilianHeidenreich** [MaximilianHeidenreich/PingBack#6]
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at server_createEvent (file:///var/task/bundled/server/chunks/event-91b0d0b8.js:97:15)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async POST (file:///var/task/bundled/server/chunks/_server.ts-59aee199.js:54:16)
at async render_endpoint (file:///var/task/bundled/server/index.js:1468:22)
at async resolve (file:///var/task/bundled/server/index.js:3812:22)
at async respond (file:///var/task/bundled/server/index.js:3705:22)
at async Array.ssr (file:///var/task/bundled/handler.js:1190:3)
```

_Note:_
- Notify Victor Cedrón#7713

**Comment by devilish-crow** [comment]
Is there any way to use the app without creating an internal error because of this bug?
